### ISSUE TITLE
Support for projects

### ISSUE THREAD

**Issue by fregante** [dt/sublime-open-in-relevant-window#1]
When running `subl Foo.sublime-project` a new window is still opened. It'd be great to have this plugin detect whether a project is already open and focus that one instead.

**Comment by franciscolourenco** [comment]
@bfred-it I've created a package which does the same for folders. I assume it should work automatically for projects. Give it a try if you still have interest and let me know if it works. I'm willing to merge both packages into one.

https://github.com/aristidesfl/sublime-prevent-duplicate-windows
